### ISSUE TITLE
List of unresolved issues

### ISSUE THREAD

**Issue by insightp25** [f-lab-edu/twitter-clone#21]
# 잔류 문제 목록

### USER
- 

### TWEET
- 

### FOLLOW
- [x] 메서드의 로직상 parameter의 followerId 혹은 followeeId 둘 중 하나의 필드값은 비어있어야 하므로 이에 대한 validation 추가 #22 

### LIKE-TWEET
- [x] 공통부분 모듈(팔로우 상태가 추가된 유저목록 등)을 추출, 중복 제거, 재사용 #18 

### (TO ALL)
- [x] exception handling 적용 #32 
- [x] PK exposure issue #20 
- [x] response models, api 전반(url, response status code 등) 디자인 전체 점검
- [x] ~~spring security 적용~~

<br></br>

---

## MINOR
(우선순위가 낮거나, 중요하지 않거나, 중요한지 아닌지 판단할 수 없거나, 또는 진행하다 보면 이후에 자연스럽게 판단이 설 것 같은 문제들)

### USER
- 

### TWEET
- [x] DELETE 등에서: boolean 등의 값을 반환 및 처리 vs exception 개념으로 처리 트레이드오프 고려, 결정 #31 
- [ ] tweet compose 시 controller/service에서 strip 처리/엄격한 validation 고려 #31 
- [ ] `tweet` entity의 `Serializable`, `@JsonSerialize`, `@JsonDeserialize`, `@JsonFormat` 리팩토링 검토

### FOLLOW
- [ ] follow mapper xml script의 가독성 개선 #22 
- [x] convertObjectToUserResponsDto 네이밍 재검토 #42 
- [x] url semantics in follow requests #41 
- [ ] sub-list 적용 가능 #44 
- [ ] `FollowResponseDto` 리팩토링

### LIKE-TWEET
- 

### (TO ALL)
- [x] 애플리케이션 빌드 후 `build/static/docs` 하위에 `index.html`가 생성되어도, 애플리케이션 실행 후 서버의 `/docs/index.html`로 접근시 404 에러가 뜨는 문제 -> 현재는 빌드시 문서 파일 `index.html`를 `/src/main/resources/static/docs`에 생성하여 접근할 수 있도록 조치 #31 
- [x] `Optional` 반환 받도록 수정: `tweetService.composeTweet()`, `likeTweetService.likeTweet()`, 요청도 tweet, likeTweet 객체가 아닌 request dto를 별도로 만들어 받게 해야(테스트용으로 generate 할 때랑 insert 할 때랑 다름 -> id 등이 별도로 생성되기 때문에. 넣을 때에 new tweet 해서 넣는 게 아닌, 그냥 준비된 tweet을 받게 하거나, 테스트용 generator에서 삽입시 생성되는 필드를 null로 해야. 삽입용 객체 생성시 foreign key를 받아 필드에 넣는 구분 VS 자체 생성한 필드를 넣는 경우 구분(실 서비스에서는 문제될 일 없으나, 테스트에서 생성한 객체와 DB에 저장되는 객체가 달라지는 문제)
- [x] user는 포스트 경우 db 잘 쓰기 됐는지 number of rows effected로 검증하는데, tweet이나 다른 도메인에 대한 쓰기 메서드 들은 안하고 그냥 반환함. 일관성 개선 필요?
- [x] test용 helper/fixture 도입 #37
